Controllers films users
ThatAnnie/java-filmorate pull request #3
Opened 2023-03-18 20:34 UTC by ThatAnnie

2023-03-19 19:26 UTC, TarasovSam requested changes
Анна, привет! В целом - все довольно хорошо) Особенно хочу отметить то, что ты сама выбрала валидацию с помощью аннотаций (что является современным и распространенным способом). Отметил то, что следует исправить и то, что можно сделать лучше!
Жду твою работу на следующую итерацию!) Если будут вопросы, пиши в пачку.

2023-03-19 19:26 UTC, TarasovSam commented on pom.xml
> +	<description>filmorate</description>
Когда описание это просто имя проекта - не лучший вариант. Расширь, пожалуйста, описание, чтобы было понятно назначение приложения.

2023-03-19 19:26 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserRepository.java
> +        if (user.getName() == null || user.getName().isEmpty()) {
Если задать имя "   ", что будет?

2023-03-19 19:26 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @NotEmpty
Почему выбрала эту аннотацию? 
Почта "  @  " пройдет валидацию?

2023-03-19 19:26 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/validator/ReleaseDate.java
> +public @interface ReleaseDate {
Собственная аннотация - очень круто!

2023-03-19 19:26 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private long id;
А для id не нужна никакая аннотация? И для пользователя тоже.

2023-03-20 16:53 UTC, ThatAnnie commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserRepository.java
> +        if (user.getName() == null || user.getName().isEmpty()) {
В качестве имени будет использован логин, т.к. "" попадет под условие user.getName().isEmpty().

2023-03-20 17:36 UTC, ThatAnnie commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @NotEmpty
Выбрала @Email для проверки корректной структуры эмейла, и чтобы нельзя было передать null добавила @NotEmpty.
Почта " @ " валидацию не пройдет.

2023-03-20 17:38 UTC, ThatAnnie commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private long id;
Добавила @NotNull для проверки на null.

2023-03-21 19:50 UTC, TarasovSam reviewed
Анна, спасибо за твои ответы и за внесение корректировок. Оставил пару комментариев на твои комментарии (тавтология).
Задание я принимаю, успеха в обучении и до следующего спринта!) Если будут вопросы, пиши в пачку.

2023-03-21 19:50 UTC, TarasovSam commented on pom.xml
> +	<description>Приложение для оценки фильмов.</description>
Да, хорошо! Все же принято не использовать кириллицу даже в описании проекта (если и пишут на русском, то в readme и при этом на английском тоже).

2023-03-23 14:07 UTC, merged