Add friends likes
ThatAnnie/java-filmorate pull request #4
Opened 2023-04-02 14:45 UTC by ThatAnnie

2023-04-02 18:10 UTC, TarasovSam requested changes
Анна, привет!
Проверил твое задание, спасибо за работу. Особо хочу отметить, что мне понравилось, что ты проводишь логирование всех действий. Оставил комментарии с тем, что можно улучшить и что нужно поправить, плюс пару вопросов)
Жду твою работу на следующую итерацию!) Если будут вопросы, пиши в пачку)

2023-04-02 18:10 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public static Integer getNumberOfLikes(Film film) {
Хорошая задумка, по сути это и есть рейтинг фильма)

2023-04-02 18:10 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private FilmService filmService;
Поле можно финализировать, чтобы обезопасится от "замены" ссылки.

2023-04-02 18:10 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private UserService userService;
Поле можно финализировать, чтобы обезопасится от "замены" ссылки.

2023-04-02 18:10 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private UserStorage userStorage;
Поле можно финализировать, чтобы обезопасится от "замены" ссылки.

2023-04-02 18:10 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +public interface FilmStorage {
Методы для FilmStorage и UserStorage идентичны, поэтому их можно выделить в интерфейс с использованием дженериков.
Тоже самое можно сделать и для InMemoryStorage, но там несколько замороченнее)
Это рекомендация к рассмотрению.

2023-04-02 19:51 UTC, ThatAnnie commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Map<String, String> handleNotFoundException(final EntityNotExistException e) {
Добавила класс ErrorHandler.

2023-04-02 20:13 UTC, ThatAnnie commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +public interface FilmStorage {
Вместо FilmStorage и UserStorage выделила один интерфейс Storage.
А насчет InMemoryStorage даже не знаю, что туда выносить. Напиши, пожалуйста, поподробнее, что ты имел в виду. Пока оставила так.

2023-04-03 18:22 UTC, TarasovSam reviewed
Анна, спасибо за то, что вносишь корректировки по рекомендациям и за твои ответы. Оставил еще пару комментариев и плюс написал в пачку.
Жду твою работу на следующую итерацию!) Если будут вопросы, пиши в пачку)

2023-04-03 18:22 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +public class ErrorHandler {
Не хватает еще одного метода (в ТЗ было указано 3, у тебя 2). Добавь еще один, пожалуйста.

2023-04-03 18:22 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/storage/Storage.java
> +public interface Storage<T> {
FilmStorage и UserStorage надо вернуть, классы как бы будут пустыми и просто экстендить интерфейс Storage (да, по сути они теперь не нужны, но они к сожалению прописаны в ТЗ).

2023-04-03 20:22 UTC, ThatAnnie commented on src/main/java/ru/yandex/practicum/filmorate/storage/Storage.java
> +public interface Storage<T> {
Вернула.

2023-04-03 20:24 UTC, ThatAnnie commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +public class ErrorHandler {
Добавила метод для ошибок валидации.

2023-04-04 17:24 UTC, TarasovSam approved these changes
Анна, привет!
Проверил твое задание, спасибо за работу и за то, что дорабатываешь код (в том числе и сверх нормы так сказать).
Задание я принимаю, успеха в обучении и до следующего спринта!) Если будут вопросы, пиши в пачку.

2023-04-08 08:35 UTC, merged