feat: add database
ThatAnnie/java-filmorate pull request #6
Opened 2023-04-22 12:00 UTC by ThatAnnie

2023-04-23 16:00 UTC, TarasovSam requested changes
Анна, привет!
Проверил твое задание, все довольно хорошо. Оставил комментарии с тем, что можно улучшить и что нужно поправить, плюс пару вопросов)
Жду твою работу на следующую итерацию!) Если будут вопросы, пиши в пачку)

PS вроде бы тебе не говорил, чтобы руками не отлавливать недостающие пробелы, отступы и прочее, используй комбинацию crtl+alt+L в каждом классе для автоформатирования.

2023-04-23 16:00 UTC, TarasovSam commented on src/main/resources/schema.sql
> +CREATE TABLE users (
Можно было бы ввести ограничение на уникальность логина и почты на уровне таблицы в БД)

create unique index if not exists USER_EMAIL_UINDEX on USERS (email);
create unique index if not exists USER_LOGIN_UINDEX on USERS (login);

2023-04-23 18:11 UTC, ThatAnnie commented
Спасибо, поправила код в соответствии с замечаниями)

2023-04-24 13:53 UTC, TarasovSam approved these changes
Анна, привет!
Проверил твое задание, все отлично. Спасибо за работу и за то, что дорабатываешь код.
Задание я принимаю, успеха в обучении и до следующего спринта!) Если будут вопросы, пиши в пачку)

2023-04-24 16:26 UTC, merged